version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: tagarasu-keiei
      POSTGRES_PASSWORD: 4XPq3vZs;#
      PGPASSWORD: password
      POSTGRES_DB:   
      TZ: "Asia/Tokyo"
    ports:
      - 55000:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 55001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: starry.eyed.chronicle@tagarasu-keiei.jp
      PGADMIN_DEFAULT_PASSWORD: 7eC3EERnvje
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin: