version: '3'
services:
  demo-app:
    build: .
    container_name: app
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/usr/local/apache2/htdocs/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - demo-app
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: tagarasu-keiei
      POSTGRES_PASSWORD: 4XPq3vZs;#
      PGPASSWORD: password
      POSTGRES_DB: tagarasu-keiei
      TZ: "Asia/Tokyo"
    ports:
      - 55000:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 55001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: starry.eyed.chronicle@tagarasu-keiei.jp
      PGADMIN_DEFAULT_PASSWORD: 7eC3EERnvje
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  postgres:
  pgadmin: