version: '3'
services:
  # --------------------------------------------
  web:
    image: jwilder/nginx-proxy:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/network_internal.conf:/etc/nginx/network_internal.conf
      - ./nginx/logs:/var/log/nginx
    environment:
       - TZ=Asia/Tokyo
    depends_on:
      - demo-app
    networks:
      - nginx_network
  # --------------------------------------------
  demo-app:
    build: .
    container_name: app
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      VIRTUAL_HOST: app.localhost
    networks:
      - nginx_network
  # --------------------------------------------
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: tagarasu-keiei
      POSTGRES_PASSWORD: 4XPq3vZs;#
      PGPASSWORD: password
      POSTGRES_DB: tagarasu-keiei
      TZ: "Asia/Tokyo"
    ports:
      - 55000:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - nginx_network
  # --------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 55001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: starry.eyed.chronicle@tagarasu-keiei.jp
      PGADMIN_DEFAULT_PASSWORD: 7eC3EERnvje
      TZ: "Asia/Tokyo"
      VIRTUAL_HOST: pgadmin.localhost
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - nginx_network
  # --------------------------------------------
volumes:
  postgres:
  pgadmin:
networks:
  nginx_network:
      driver: bridge
