version: 1

formatters:
  default:
    format: '%(asctime)s [%(name)s] [%(levelname)s] %(message)s at %(filename)s  %(lineno)d'
    datefmt: '%Y/%m/%d %H:%M:%S %Z'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    filename: './log/myapp.log'
    formatter: default
    when: 'MIDNIGHT'
    backupCount: 7
loggers:
  backend:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console, file]
